import type { TokenFile } from '../schema.js';
import { hexToHsl, isRgba, rgbaToHsl } from '../utils/colors.js';

export interface CssOptions {
  /** Color output format. Default: 'hsl' */
  format?: 'hex' | 'hsl';
  /** CSS variable prefix. Default: '--' */
  prefix?: string;
  /** Selector to scope variables under. Default: ':root' */
  selector?: string;
}

/**
 * Format a TokenFile as CSS custom properties.
 *
 * Colors are converted to HSL (space-separated) for Tailwind compatibility.
 * Glass colors retain their rgba format since they carry alpha.
 */
export function formatCss(tokens: TokenFile, options: CssOptions = {}): string {
  const { format = 'hsl', prefix = '--', selector = ':root' } = options;

  const lines: string[] = [];
  const indent = '  ';

  const color = (value: string): string => {
    if (isRgba(value)) return format === 'hsl' ? rgbaToHsl(value) : value;
    return format === 'hsl' ? hexToHsl(value) : value;
  };

  lines.push(`/* ${tokens.name} v${tokens.version} — generated by token-forge */`);
  lines.push(`${selector} {`);

  // --- Colors ---
  lines.push(`${indent}/* Colors */`);
  lines.push(`${indent}${prefix}background: ${color(tokens.colors.background)};`);
  lines.push(`${indent}${prefix}surface: ${color(tokens.colors.surface)};`);
  if (tokens.colors.surface_variant) {
    lines.push(`${indent}${prefix}surface-variant: ${color(tokens.colors.surface_variant)};`);
  }
  if (tokens.colors.edge) {
    lines.push(`${indent}${prefix}edge: ${color(tokens.colors.edge)};`);
  }
  if (tokens.colors.edge_light) {
    lines.push(`${indent}${prefix}edge-light: ${color(tokens.colors.edge_light)};`);
  }
  lines.push(`${indent}${prefix}primary: ${color(tokens.colors.primary)};`);
  if (tokens.colors.primary_light) {
    lines.push(`${indent}${prefix}primary-light: ${color(tokens.colors.primary_light)};`);
  }
  if (tokens.colors.primary_glow) {
    lines.push(`${indent}${prefix}primary-glow: ${color(tokens.colors.primary_glow)};`);
  }
  if (tokens.colors.tertiary) {
    lines.push(`${indent}${prefix}tertiary: ${color(tokens.colors.tertiary)};`);
  }
  if (tokens.colors.tertiary_light) {
    lines.push(`${indent}${prefix}tertiary-light: ${color(tokens.colors.tertiary_light)};`);
  }

  // Text
  lines.push('');
  lines.push(`${indent}/* Text */`);
  lines.push(`${indent}${prefix}text-primary: ${color(tokens.colors.text.primary)};`);
  lines.push(`${indent}${prefix}text-secondary: ${color(tokens.colors.text.secondary)};`);
  lines.push(`${indent}${prefix}text-muted: ${color(tokens.colors.text.muted)};`);

  // Glass
  lines.push('');
  lines.push(`${indent}/* Glass */`);
  lines.push(`${indent}${prefix}glass-bg: ${color(tokens.colors.glass.background)};`);
  lines.push(`${indent}${prefix}glass-border: ${color(tokens.colors.glass.border)};`);
  lines.push(`${indent}${prefix}glass-highlight: ${color(tokens.colors.glass.highlight)};`);

  // Status
  lines.push('');
  lines.push(`${indent}/* Status */`);
  lines.push(`${indent}${prefix}status-success: ${color(tokens.colors.status.success)};`);
  lines.push(`${indent}${prefix}status-warning: ${color(tokens.colors.status.warning)};`);
  lines.push(`${indent}${prefix}status-error: ${color(tokens.colors.status.error)};`);
  if (tokens.colors.status.info) {
    lines.push(`${indent}${prefix}status-info: ${color(tokens.colors.status.info)};`);
  }

  // Canvas
  if (tokens.colors.canvas) {
    lines.push('');
    lines.push(`${indent}/* Canvas */`);
    lines.push(`${indent}${prefix}canvas-bg: ${color(tokens.colors.canvas.background)};`);
    lines.push(`${indent}${prefix}canvas-grid: ${color(tokens.colors.canvas.grid)};`);
  }

  // --- Spacing ---
  lines.push('');
  lines.push(`${indent}/* Spacing */`);
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`${indent}${prefix}spacing-${key}: ${value}px;`);
  }

  // --- Radii ---
  lines.push('');
  lines.push(`${indent}/* Radii */`);
  for (const [key, value] of Object.entries(tokens.radii)) {
    const unit = key === 'full' ? 'px' : 'px';
    lines.push(`${indent}${prefix}radius-${key}: ${value}${unit};`);
  }

  // --- Typography ---
  lines.push('');
  lines.push(`${indent}/* Typography */`);
  lines.push(`${indent}${prefix}font-family: '${tokens.typography.family}', sans-serif;`);
  if (tokens.typography.display_family) {
    lines.push(`${indent}${prefix}font-display: '${tokens.typography.display_family}', serif;`);
  }
  if (tokens.typography.mono_family) {
    lines.push(`${indent}${prefix}font-mono: '${tokens.typography.mono_family}', monospace;`);
  }

  // Type scales
  if (tokens.typography.scales) {
    lines.push('');
    lines.push(`${indent}/* Type Scales */`);
    for (const [name, scale] of Object.entries(tokens.typography.scales)) {
      const cssName = name.replace(/_/g, '-');
      lines.push(`${indent}${prefix}font-size-${cssName}: ${scale.size}px;`);
      lines.push(`${indent}${prefix}font-weight-${cssName}: ${scale.weight};`);
      if (scale.spacing !== undefined) {
        lines.push(`${indent}${prefix}letter-spacing-${cssName}: ${scale.spacing}px;`);
      }
    }
  }

  // --- Glass ---
  lines.push('');
  lines.push(`${indent}/* Glass */`);
  lines.push(`${indent}${prefix}glass-blur: ${tokens.glass.blur_sigma}px;`);
  lines.push(`${indent}${prefix}glass-border-width: ${tokens.glass.border_width}px;`);

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
