import { resolveTokens } from '../resolver.js';
import type { AnyTokenFile, ResolvedTokenSet, TokenMap } from '../schema.js';
import { hexToHsl, isRgba, rgbaToHsl } from '../utils/colors.js';

export interface CssOptions {
  /** Color output format. Default: 'hsl' */
  format?: 'hex' | 'hsl';
  /** CSS variable prefix. Default: '--' */
  prefix?: string;
  /** Selector to scope variables under. Default: ':root' */
  selector?: string;
}

/**
 * Format a TokenFile as CSS custom properties.
 *
 * Colors are converted to HSL (space-separated) for Tailwind compatibility.
 * Glass colors retain their rgba format since they carry alpha.
 */
export function formatCss(tokens: AnyTokenFile, options: CssOptions = {}): string {
  const resolved = resolveTokens(tokens);
  const tokensLegacy = resolved.legacy;
  const { format = 'hsl', selector = ':root' } = options;
  const legacyPrefix = options.prefix ?? '--';
  const v2Prefix = options.prefix ?? cssProjectionPrefix(resolved) ?? '--rh-';

  const lines: string[] = [];
  const indent = '  ';

  const color = (value: string): string => {
    if (!isColorLike(value)) return value;
    if (isRgba(value)) return format === 'hsl' ? rgbaToHsl(value) : value;
    return format === 'hsl' ? hexToHsl(value) : value;
  };

  lines.push(`/* ${tokensLegacy.name} v${tokensLegacy.version} — generated by token-forge */`);
  lines.push(`${selector} {`);

  // --- Colors ---
  lines.push(`${indent}/* Colors */`);
  lines.push(`${indent}${legacyPrefix}background: ${color(tokensLegacy.colors.background)};`);
  lines.push(`${indent}${legacyPrefix}surface: ${color(tokensLegacy.colors.surface)};`);
  if (tokensLegacy.colors.surface_variant) {
    lines.push(`${indent}${legacyPrefix}surface-variant: ${color(tokensLegacy.colors.surface_variant)};`);
  }
  if (tokensLegacy.colors.edge) {
    lines.push(`${indent}${legacyPrefix}edge: ${color(tokensLegacy.colors.edge)};`);
  }
  if (tokensLegacy.colors.edge_light) {
    lines.push(`${indent}${legacyPrefix}edge-light: ${color(tokensLegacy.colors.edge_light)};`);
  }
  lines.push(`${indent}${legacyPrefix}primary: ${color(tokensLegacy.colors.primary)};`);
  if (tokensLegacy.colors.primary_light) {
    lines.push(`${indent}${legacyPrefix}primary-light: ${color(tokensLegacy.colors.primary_light)};`);
  }
  if (tokensLegacy.colors.primary_glow) {
    lines.push(`${indent}${legacyPrefix}primary-glow: ${color(tokensLegacy.colors.primary_glow)};`);
  }
  if (tokensLegacy.colors.tertiary) {
    lines.push(`${indent}${legacyPrefix}tertiary: ${color(tokensLegacy.colors.tertiary)};`);
  }
  if (tokensLegacy.colors.tertiary_light) {
    lines.push(`${indent}${legacyPrefix}tertiary-light: ${color(tokensLegacy.colors.tertiary_light)};`);
  }

  // Text
  lines.push('');
  lines.push(`${indent}/* Text */`);
  lines.push(`${indent}${legacyPrefix}text-primary: ${color(tokensLegacy.colors.text.primary)};`);
  lines.push(`${indent}${legacyPrefix}text-secondary: ${color(tokensLegacy.colors.text.secondary)};`);
  lines.push(`${indent}${legacyPrefix}text-muted: ${color(tokensLegacy.colors.text.muted)};`);

  // Glass
  lines.push('');
  lines.push(`${indent}/* Glass */`);
  lines.push(`${indent}${legacyPrefix}glass-bg: ${color(tokensLegacy.colors.glass.background)};`);
  lines.push(`${indent}${legacyPrefix}glass-border: ${color(tokensLegacy.colors.glass.border)};`);
  lines.push(`${indent}${legacyPrefix}glass-highlight: ${color(tokensLegacy.colors.glass.highlight)};`);

  // Status
  lines.push('');
  lines.push(`${indent}/* Status */`);
  lines.push(`${indent}${legacyPrefix}status-success: ${color(tokensLegacy.colors.status.success)};`);
  lines.push(`${indent}${legacyPrefix}status-warning: ${color(tokensLegacy.colors.status.warning)};`);
  lines.push(`${indent}${legacyPrefix}status-error: ${color(tokensLegacy.colors.status.error)};`);
  if (tokensLegacy.colors.status.info) {
    lines.push(`${indent}${legacyPrefix}status-info: ${color(tokensLegacy.colors.status.info)};`);
  }

  // Canvas
  if (tokensLegacy.colors.canvas) {
    lines.push('');
    lines.push(`${indent}/* Canvas */`);
    lines.push(`${indent}${legacyPrefix}canvas-bg: ${color(tokensLegacy.colors.canvas.background)};`);
    lines.push(`${indent}${legacyPrefix}canvas-grid: ${color(tokensLegacy.colors.canvas.grid)};`);
  }

  // --- Spacing ---
  lines.push('');
  lines.push(`${indent}/* Spacing */`);
  for (const [key, value] of Object.entries(tokensLegacy.spacing)) {
    lines.push(`${indent}${legacyPrefix}spacing-${key}: ${value}px;`);
  }

  // --- Radii ---
  lines.push('');
  lines.push(`${indent}/* Radii */`);
  for (const [key, value] of Object.entries(tokensLegacy.radii)) {
    const unit = key === 'full' ? 'px' : 'px';
    lines.push(`${indent}${legacyPrefix}radius-${key}: ${value}${unit};`);
  }

  // --- Typography ---
  lines.push('');
  lines.push(`${indent}/* Typography */`);
  lines.push(`${indent}${legacyPrefix}font-family: '${tokensLegacy.typography.family}', sans-serif;`);
  if (tokensLegacy.typography.display_family) {
    lines.push(`${indent}${legacyPrefix}font-display: '${tokensLegacy.typography.display_family}', serif;`);
  }
  if (tokensLegacy.typography.mono_family) {
    lines.push(`${indent}${legacyPrefix}font-mono: '${tokensLegacy.typography.mono_family}', monospace;`);
  }

  // Type scales
  if (tokensLegacy.typography.scales) {
    lines.push('');
    lines.push(`${indent}/* Type Scales */`);
    for (const [name, scale] of Object.entries(tokensLegacy.typography.scales)) {
      const cssName = name.replace(/_/g, '-');
      lines.push(`${indent}${legacyPrefix}font-size-${cssName}: ${scale.size}px;`);
      lines.push(`${indent}${legacyPrefix}font-weight-${cssName}: ${scale.weight};`);
      if (scale.spacing !== undefined) {
        lines.push(`${indent}${legacyPrefix}letter-spacing-${cssName}: ${scale.spacing}px;`);
      }
    }
  }

  // --- Glass ---
  lines.push('');
  lines.push(`${indent}/* Glass */`);
  lines.push(`${indent}${legacyPrefix}glass-blur: ${tokensLegacy.glass.blur_sigma}px;`);
  lines.push(`${indent}${legacyPrefix}glass-border-width: ${tokensLegacy.glass.border_width}px;`);

  if (resolved.sourceKind === 'v2') {
    lines.push('');
    lines.push(`${indent}/* V2 Primitives */`);
    emitStringLeaves(lines, indent, v2Prefix, 'color', tokenMapAt(resolved.primitives, 'color'), color);

    lines.push('');
    lines.push(`${indent}/* V2 Roles */`);
    emitStringLeaves(lines, indent, v2Prefix, 'surface', tokenMapAt(resolved.roles, 'surface'), color);
    emitStringLeaves(lines, indent, v2Prefix, 'border', tokenMapAt(resolved.roles, 'border'), color);
    emitActionVariables(lines, indent, v2Prefix, resolved, color);

    lines.push('');
    lines.push(`${indent}/* V2 States */`);
    emitStateColorVariables(lines, indent, v2Prefix, 'agent', resolved, color);
    emitStateColorVariables(lines, indent, v2Prefix, 'contract', resolved, color);
    emitStateColorVariables(lines, indent, v2Prefix, 'runtime', resolved, color);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function isColorLike(value: string): boolean {
  return value.startsWith('#') || isRgba(value);
}

function cssProjectionPrefix(resolved: ResolvedTokenSet): string | undefined {
  const css = resolved.projections?.css;
  return css && typeof css === 'object' && !Array.isArray(css) && typeof css.prefix === 'string'
    ? css.prefix
    : undefined;
}

function tokenMapAt(map: TokenMap, key: string): TokenMap {
  const value = map[key];
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

function emitStringLeaves(
  lines: string[],
  indent: string,
  prefix: string,
  namespace: string,
  map: TokenMap,
  transform: (value: string) => string
): void {
  for (const [key, value] of Object.entries(map)) {
    const name = `${namespace}-${key.replace(/_/g, '-')}`;
    if (typeof value === 'string') {
      lines.push(`${indent}${prefix}${name}: ${transform(value)};`);
    }
  }
}

function emitActionVariables(
  lines: string[],
  indent: string,
  prefix: string,
  resolved: ResolvedTokenSet,
  transform: (value: string) => string
): void {
  const action = tokenMapAt(resolved.roles, 'action');
  for (const [variant, rawConfig] of Object.entries(action)) {
    if (!rawConfig || typeof rawConfig !== 'object' || Array.isArray(rawConfig)) continue;
    for (const [key, value] of Object.entries(rawConfig)) {
      if (typeof value !== 'string') continue;
      const suffix = key === 'background' ? 'bg' : key === 'foreground' ? 'fg' : key.replace(/_/g, '-');
      lines.push(`${indent}${prefix}action-${variant.replace(/_/g, '-')}-${suffix}: ${transform(value)};`);
    }
  }
}

function emitStateColorVariables(
  lines: string[],
  indent: string,
  prefix: string,
  namespace: string,
  resolved: ResolvedTokenSet,
  transform: (value: string) => string
): void {
  const stateGroup = tokenMapAt(resolved.states, namespace);
  for (const [state, rawConfig] of Object.entries(stateGroup)) {
    if (!rawConfig || typeof rawConfig !== 'object' || Array.isArray(rawConfig)) continue;
    const colorValue = rawConfig.color;
    if (typeof colorValue === 'string') {
      lines.push(`${indent}${prefix}${namespace}-${state.replace(/_/g, '-')}: ${transform(colorValue)};`);
    }
  }
}
