import type { TokenFile } from '../schema.js';

/**
 * Format a TokenFile as a Tailwind CSS theme extension.
 *
 * Colors reference CSS custom properties (set by the CSS formatter),
 * so both outputs are designed to work together:
 *   1. tokens.css defines the CSS vars
 *   2. tailwind.tokens.js maps Tailwind classes to those vars
 */
export function formatTailwind(tokens: TokenFile): string {
  const colors: Record<string, string> = {
    background: 'hsl(var(--background))',
    surface: 'hsl(var(--surface))',
    primary: 'hsl(var(--primary))',
  };

  if (tokens.colors.surface_variant) colors['surface-variant'] = 'hsl(var(--surface-variant))';
  if (tokens.colors.edge) colors.edge = 'hsl(var(--edge))';
  if (tokens.colors.edge_light) colors['edge-light'] = 'hsl(var(--edge-light))';
  if (tokens.colors.primary_light) colors['primary-light'] = 'hsl(var(--primary-light))';
  if (tokens.colors.primary_glow) colors['primary-glow'] = 'hsl(var(--primary-glow))';
  if (tokens.colors.tertiary) colors.tertiary = 'hsl(var(--tertiary))';
  if (tokens.colors.tertiary_light) colors['tertiary-light'] = 'hsl(var(--tertiary-light))';

  colors['text-primary'] = 'hsl(var(--text-primary))';
  colors['text-secondary'] = 'hsl(var(--text-secondary))';
  colors['text-muted'] = 'hsl(var(--text-muted))';

  colors['status-success'] = 'hsl(var(--status-success))';
  colors['status-warning'] = 'hsl(var(--status-warning))';
  colors['status-error'] = 'hsl(var(--status-error))';
  if (tokens.colors.status.info) colors['status-info'] = 'hsl(var(--status-info))';

  const spacing: Record<string, string> = {};
  for (const key of Object.keys(tokens.spacing)) {
    spacing[key] = `var(--spacing-${key})`;
  }

  const borderRadius: Record<string, string> = {};
  for (const key of Object.keys(tokens.radii)) {
    borderRadius[key] = `var(--radius-${key})`;
  }

  const fontFamily: Record<string, string[]> = {
    sans: [`var(--font-family)`, 'sans-serif'],
  };
  if (tokens.typography.display_family) {
    fontFamily.display = [`var(--font-display)`, 'serif'];
  }
  if (tokens.typography.mono_family) {
    fontFamily.mono = [`var(--font-mono)`, 'monospace'];
  }

  const config = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        fontFamily,
      },
    },
  };

  const lines: string[] = [];
  lines.push(`// ${tokens.name} v${tokens.version} — generated by token-forge`);
  lines.push('');
  lines.push(`export default ${JSON.stringify(config, null, 2)};`);
  lines.push('');

  return lines.join('\n');
}
